In [1]:
import numpy as np

 # Варіант №3

## Завдання №1

### Виконати набір вправ. Всі завдання виконати двома способами:
* З використанням універсальних функцій бібліотеки NumPy
* За допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо)
* Для обох випадків підрахувати час виконання скрипту та зробити висновки

### 1) Вводиться число n. Вивести масив розміром n*n, в якому по діагоналі йдуть числа від 1 до n, а всі інші дорівнюють нулю

In [8]:
%%time
import numpy as np
import time

def task_1(n):
    start_time = time.time()
    diagonal_matrix = np.diag(np.arange(1, n + 1))
    end_time = time.time()
    execution_time = end_time - start_time
    return diagonal_matrix, execution_time

n = int(input("Введіть число n: "))
result_numpy, time_numpy = create_diagonal_matrix_numpy(n)
print("Результат за допомогою NumPy:")
print(result_numpy)

Введіть число n:  5


Результат за допомогою NumPy:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
Час виконання (NumPy): 0.0 сек
CPU times: total: 0 ns
Wall time: 1.57 s


In [9]:
%%time
def task_1(n):
    start_time = time.time()
    diagonal_matrix = [[0] * n for _ in range(n)]
    for i in range(n):
        diagonal_matrix[i][i] = i + 1
    end_time = time.time()
    execution_time = end_time - start_time
    return diagonal_matrix, execution_time

n = int(input("Введіть число n: "))
result_iterative, time_iterative = create_diagonal_matrix_iterative(n)
print("Результат за допомогою ітеративних конструкцій:")
for row in result_iterative:
    print(row)

Введіть число n:  5


Результат за допомогою ітеративних конструкцій:
[1, 0, 0, 0, 0]
[0, 2, 0, 0, 0]
[0, 0, 3, 0, 0]
[0, 0, 0, 4, 0]
[0, 0, 0, 0, 5]
CPU times: total: 15.6 ms
Wall time: 1.38 s


### 3) Вводяться чотири числа n, m, r, c. Вивести масив розміру n*m, в якому в кожному рядку з номером r і в кожному стовпчику з номером c стоять 0, а інші елементи дорівнюють 1.

In [11]:
%%time

import numpy as np
import time

def task_3(n, m, r, c):
    start_time = time.time()
    custom_array = np.ones((n, m), dtype=int)
    custom_array[r, :] = 0
    custom_array[:, c] = 0
    end_time = time.time()
    execution_time = end_time - start_time
    return custom_array, execution_time

n = int(input("Введіть число n: "))
m = int(input("Введіть число m: "))
r = int(input("Введіть номер рядка r: "))
c = int(input("Введіть номер стовпчика c: "))

result_numpy, time_numpy = task_3(n, m, r, c)
print("Результат за допомогою NumPy:")
print(result_numpy)

Введіть число n:  4
Введіть число m:  4
Введіть номер рядка r:  2
Введіть номер стовпчика c:  2


Результат за допомогою NumPy:
[[1 1 0 1]
 [1 1 0 1]
 [0 0 0 0]
 [1 1 0 1]]
CPU times: total: 15.6 ms
Wall time: 2.72 s


In [14]:
%%time

def task_3(n, m, r, c):
    start_time = time.time()
    custom_array = [[1] * m for _ in range(n)]
    for i in range(n):
        custom_array[i][c] = 0
    for j in range(m):
        custom_array[r][j] = 0
    end_time = time.time()
    execution_time = end_time - start_time
    return custom_array, execution_time

n = int(input("Введіть число n: "))
m = int(input("Введіть число m: "))
r = int(input("Введіть номер рядка r: "))
c = int(input("Введіть номер стовпчика c: "))

result_iterative, time_iterative = task_3(n, m, r, c)
print("Результат за допомогою ітеративних конструкцій:")
for row in result_iterative:
    print(row)

Введіть число n:  4
Введіть число m:  4
Введіть номер рядка r:  2
Введіть номер стовпчика c:  2


Результат за допомогою ітеративних конструкцій:
[1, 1, 0, 1]
[1, 1, 0, 1]
[0, 0, 0, 0]
[1, 1, 0, 1]
CPU times: total: 15.6 ms
Wall time: 2.97 s


### 6) З клавіатури вводиться масив. Замінити всі ненульові елементи на -1.

In [15]:
%%time

import numpy as np
import time

def task_6(input_array):
    start_time = time.time()
    modified_array = np.where(input_array != 0, -1, input_array)
    end_time = time.time()
    execution_time = end_time - start_time
    return modified_array, execution_time

# Введення масиву з клавіатури
input_array = np.array(input("Введіть масив чисел, розділених пробілами: ").split(), dtype=int)

result_numpy, time_numpy = task_6(input_array)
print("Результат за допомогою NumPy:")
print(result_numpy)

Введіть масив чисел, розділених пробілами:  -5 -3 1 -3 0 0 1 3 -2


Результат за допомогою NumPy:
[-1 -1 -1 -1  0  0 -1 -1 -1]
CPU times: total: 0 ns
Wall time: 11.2 s


In [16]:
%%time

def task_6(input_array):
    start_time = time.time()
    modified_array = [-1 if x != 0 else 0 for x in input_array]
    end_time = time.time()
    execution_time = end_time - start_time
    return modified_array, execution_time

# Введення масиву з клавіатури
input_array = list(map(int, input("Введіть масив чисел, розділених пробілами: ").split()))

result_iterative, time_iterative = task_6(input_array)
print("Результат за допомогою ітеративних конструкцій:")
print(result_iterative)

Введіть масив чисел, розділених пробілами:  -5 -3 1 -3 0 0 1 3 -2


Результат за допомогою ітеративних конструкцій:
[-1, -1, -1, -1, 0, 0, -1, -1, -1]
CPU times: total: 0 ns
Wall time: 12.9 s


### 7) З клавіатури вводиться масив. Замінити всі нульові елементи на -1.

In [2]:
%%time

import numpy as np
import time

def task_7(input_array):
    start_time = time.time()
    modified_array = np.where(input_array == 0, -1, input_array)
    end_time = time.time()
    execution_time = end_time - start_time
    return modified_array, execution_time

# Введення масиву з клавіатури
input_array = np.array(input("Введіть масив чисел, розділених пробілами: ").split(), dtype=int)

result_numpy, time_numpy = task_7(input_array)
print("Результат за допомогою NumPy:")
print(result_numpy)

Введіть масив чисел, розділених пробілами:  -5 0 0 1 0 2


Результат за допомогою NumPy:
[-5 -1 -1  1 -1  2]
CPU times: total: 0 ns
Wall time: 7.45 s


In [3]:
%%time

def task_7(input_array):
    start_time = time.time()
    modified_array = [-1 if x == 0 else x for x in input_array]
    end_time = time.time()
    execution_time = end_time - start_time
    return modified_array, execution_time

# Введення масиву з клавіатури
input_array = list(map(int, input("Введіть масив чисел, розділених пробілами: ").split()))

result_iterative, time_iterative = task_7(input_array)
print("Результат за допомогою ітеративних конструкцій:")
print(result_iterative)

Введіть масив чисел, розділених пробілами:  -5 0 0 1 0 2


Результат за допомогою ітеративних конструкцій:
[-5, -1, -1, 1, -1, 2]
CPU times: total: 0 ns
Wall time: 6.11 s


### 7) З клавіатури вводиться масив. Підрахувати в ньому кількість нульових та ненульових елементів.

In [5]:
%%time

import numpy as np
import time

def task_8_numpy(input_array):
    start_time = time.time()
    count_zeros = np.count_nonzero(input_array == 0)
    count_non_zeros = np.count_nonzero(input_array != 0)
    end_time = time.time()
    execution_time = end_time - start_time
    return count_zeros, count_non_zeros, execution_time

# Введення масиву з клавіатури
input_array = np.array(input("Введіть масив чисел, розділених пробілами: ").split(), dtype=int)

zeros_numpy, non_zeros_numpy, time_numpy = task_8_numpy(input_array)
print("Кількість нульових елементів (NumPy):", zeros_numpy)
print("Кількість ненульових елементів (NumPy):", non_zeros_numpy)

Введіть масив чисел, розділених пробілами:  0 1 0 1 4 -3 -2 -10


Кількість нульових елементів (NumPy): 2
Кількість ненульових елементів (NumPy): 6
CPU times: total: 0 ns
Wall time: 12.4 s


In [6]:
%%time

def task_8_iterative(input_array):
    start_time = time.time()
    count_zeros = sum(1 for x in input_array if x == 0)
    count_non_zeros = sum(1 for x in input_array if x != 0)
    end_time = time.time()
    execution_time = end_time - start_time
    return count_zeros, count_non_zeros, execution_time

# Введення масиву з клавіатури
input_array = list(map(int, input("Введіть масив чисел, розділених пробілами: ").split()))

zeros_iterative, non_zeros_iterative, time_iterative = task_8_iterative(input_array)
print("Кількість нульових елементів (ітеративно):", zeros_iterative)
print("Кількість ненульових елементів (ітеративно):", non_zeros_iterative)

Введіть масив чисел, розділених пробілами:  -10 3 4 -10 -2 3 4


Кількість нульових елементів (ітеративно): 0
Кількість ненульових елементів (ітеративно): 7
CPU times: total: 0 ns
Wall time: 8.48 s


### 11) Cтворити масив з одиниць розміром n*n та додати до нього рамку, що утворюється з 0.

In [9]:
%%time

import numpy as np
import time

def task_11_numpy(n):
    start_time = time.time()
    ones_array = np.ones((n, n), dtype=int)
    ones_array[0,:] = 0
    ones_array[-1,:] = 0
    ones_array[:,0] = 0
    ones_array[:,-1] = 0
    end_time = time.time()
    execution_time = end_time - start_time
    return ones_array, execution_time

# Введення розміру масиву з клавіатури
n = int(input("Введіть розмір масиву n: "))

result_numpy, time_numpy = task_11_numpy(n)
print("Результат за допомогою NumPy:")
print(result_numpy)

Введіть розмір масиву n:  5


Результат за допомогою NumPy:
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
CPU times: total: 0 ns
Wall time: 2.21 s


In [10]:
%%time 

def task_11_iterative(n):
    start_time = time.time()
    ones_array = [[1] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            if i == 0 or i == n - 1 or j == 0 or j == n - 1:
                ones_array[i][j] = 0
    end_time = time.time()
    execution_time = end_time - start_time
    return ones_array, execution_time

# Введення розміру масиву з клавіатури
n = int(input("Введіть розмір масиву n: "))

result_iterative, time_iterative = task_11_iterative(n)
print("Результат за допомогою ітеративних конструкцій:")
for row in result_iterative:
    print(row)
print("Час виконання (ітеративно):", time_iterative, "сек")

Введіть розмір масиву n:  5


Результат за допомогою ітеративних конструкцій:
[0, 0, 0, 0, 0]
[0, 1, 1, 1, 0]
[0, 1, 1, 1, 0]
[0, 1, 1, 1, 0]
[0, 0, 0, 0, 0]
Час виконання (ітеративно): 0.0 сек
CPU times: total: 0 ns
Wall time: 1.33 s


### 16) Заповнити вектор значеннями від 0 до n. Всі значення, що більші за n/4 та менші за 3n/4 замінити нулями. 

In [11]:
%%time

import numpy as np
import time

def task_16_numpy(n):
    start_time = time.time()
    vector = np.arange(n)
    vector[(vector > n/4) & (vector < 3*n/4)] = 0
    end_time = time.time()
    execution_time = end_time - start_time
    return vector, execution_time

# Введення значення n з клавіатури
n = int(input("Введіть значення n: "))

result_numpy, time_numpy = task_16_numpy(n)
print("Результат за допомогою NumPy:")
print(result_numpy)
print("Час виконання (NumPy):", time_numpy, "сек")

Введіть значення n:  5


Результат за допомогою NumPy:
[0 1 0 0 4]
Час виконання (NumPy): 0.0010309219360351562 сек
CPU times: total: 15.6 ms
Wall time: 2.67 s


In [12]:
%%time

def task_16_iterative(n):
    start_time = time.time()
    vector = [i if i <= n/4 or i >= 3*n/4 else 0 for i in range(n)]
    end_time = time.time()
    execution_time = end_time - start_time
    return vector, execution_time

# Введення значення n з клавіатури
n = int(input("Введіть значення n: "))

result_iterative, time_iterative = task_16_iterative(n)
print("Результат за допомогою ітеративних конструкцій:")
print(result_iterative)
print("Час виконання (ітеративно):", time_iterative, "сек")

Введіть значення n:  5


Результат за допомогою ітеративних конструкцій:
[0, 1, 0, 0, 4]
Час виконання (ітеративно): 0.0 сек
CPU times: total: 0 ns
Wall time: 2.02 s


### 18) Згенерувати вектор з n випадкових чисел від 0 до 99. Визначити кількість унікальних чисел в послідовності.

In [13]:
%%time

import numpy as np
import time

def task_18_numpy(n):
    start_time = time.time()
    vector = np.random.randint(0, 100, size=n)
    unique_count = len(np.unique(vector))
    end_time = time.time()
    execution_time = end_time - start_time
    return unique_count, execution_time

# Введення значення n з клавіатури
n = int(input("Введіть значення n: "))

result_numpy, time_numpy = task_18_numpy(n)
print("Кількість унікальних чисел за допомогою NumPy:", result_numpy)

Введіть значення n:  5


Кількість унікальних чисел за допомогою NumPy: 5
CPU times: total: 0 ns
Wall time: 2.25 s


In [14]:
%%time

def task_18_iterative(n):
    start_time = time.time()
    vector = [np.random.randint(0, 100) for _ in range(n)]
    unique_count = len(set(vector))
    end_time = time.time()
    execution_time = end_time - start_time
    return unique_count, execution_time

# Введення значення n з клавіатури
n = int(input("Введіть значення n: "))

result_iterative, time_iterative = task_18_iterative(n)
print("Кількість унікальних чисел за допомогою ітеративних конструкцій:", result_iterative)

Введіть значення n:  5


Кількість унікальних чисел за допомогою ітеративних конструкцій: 5
CPU times: total: 15.6 ms
Wall time: 2.27 s


### 19) Згенерувати вектор із n елементів, які рівномірно розміщені на інтервалі (0, 1), тобто обидва кінці інтервалу не включені. Значення вивести до трьох знаків після коми.

In [15]:
%%time

import numpy as np
import time

def task_19_numpy(n):
    start_time = time.time()
    vector = np.linspace(0, 1, n, endpoint=False)[1:]
    end_time = time.time()
    execution_time = end_time - start_time
    return np.around(vector, 3), execution_time

# Введення значення n з клавіатури
n = int(input("Введіть значення n: "))

result_numpy, time_numpy = task_19_numpy(n)
print("Вектор за допомогою NumPy:")
print(result_numpy)

Введіть значення n:  5


Вектор за допомогою NumPy:
[0.2 0.4 0.6 0.8]
CPU times: total: 0 ns
Wall time: 7.44 s


In [16]:
%%time

def task_19_iterative(n):
    start_time = time.time()
    interval_size = 1 / n
    vector = [round(i * interval_size, 3) for i in range(1, n)]
    end_time = time.time()
    execution_time = end_time - start_time
    return vector, execution_time

# Введення значення n з клавіатури
n = int(input("Введіть значення n: "))

result_iterative, time_iterative = task_19_iterative(n)
print("Вектор за допомогою ітеративних конструкцій:")
print(result_iterative)

Введіть значення n:  5


Вектор за допомогою ітеративних конструкцій:
[0.2, 0.4, 0.6, 0.8]
CPU times: total: 0 ns
Wall time: 1.18 s


## Завдання №2

### Розв'язати систему алгебраїчних рівнянь з використанням формул Крамера й виконати перевірку за допомогою:
* Матричного множення
* Матричного множення
* Функції numpy.linalg.solve()
>Порівняти всі рішення за допомогою функції numpy.allclose()

In [17]:
# Коефіцієнти системи
coefficients = [
    [1, 2, 3, 4],
    [2, 1, 2, 3],
    [3, 2, 1, 2],
    [4, 3, 2, 1]
];
constants = [5, 1, 1, -5];

# За допомогою формул Крамера
def solve_system_cramer(coefficients, constants):
    main_determinant = np.linalg.det(coefficients)

    if main_determinant == 0:
        raise ValueError("Розв'зок відсутній")

    solutions = []
    for i in range(len(coefficients)):
        modified_matrix = np.copy(coefficients)
        modified_matrix[:, i] = constants
        solutions.append(round((np.linalg.det(modified_matrix) / main_determinant), 3))

    return solutions

# Множення матриць
def solve_system_matrix_multiplication(coefficients, constants):
    inverse_matrix = np.linalg.inv(coefficients)
    solutions = np.dot(inverse_matrix, constants)
    return solutions

# numpy.linalg.solve()
def solve_system_numpy(coefficients, constants):
    solutions = np.linalg.solve(coefficients, constants)
    return solutions


cramer_solutions = solve_system_cramer(coefficients, constants)
matrix_multiplication_solutions = solve_system_matrix_multiplication(coefficients, constants)
numpy_solutions = solve_system_numpy(coefficients, constants)

# Порівняння розв'язків
are_close_cramer_matrix = np.allclose(cramer_solutions, matrix_multiplication_solutions)
are_close_cramer_numpy = np.allclose(cramer_solutions, numpy_solutions)

# Вивід результатів
print("Крамер:", cramer_solutions)
print("Матричне множення:", matrix_multiplication_solutions)
print("numpy.linalg.solve():", numpy_solutions)

# Вивід порівняння
print("\nПорівняння Крамера і матричного множення:", are_close_cramer_matrix)
print("Порівняння Крамера і numpy.linalg.solve():", are_close_cramer_numpy)

Крамер: [-2.0, 2.0, -3.0, 3.0]
Матричне множення: [-2.  2. -3.  3.]
numpy.linalg.solve(): [-2.  2. -3.  3.]

Порівняння Крамера і матричного множення: True
Порівняння Крамера і numpy.linalg.solve(): True


## Завдання №3
### Обчислити значення матричного виразу:
* З використанням універсальних функцій бібліотеки NumPy
* За допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо)
* Для обох випадків підрахувати час виконання скрипту та зробити висновки

>Порівняти всі рішення за допомогою функції numpy.allclose()

In [23]:
import numpy as np
import time

# Функція для розрахунку виразу з використанням універсальних функцій NumPy
def calculate_expression_numpy(A, B):
    A = np.array(A)
    B = np.array(B)
    return 2 * np.multiply(np.subtract(A, B), np.add(np.square(A), B))

result_numpy = calculate_expression_numpy(A, B)
print("Result using NumPy:\n", result_numpy)

# Функція для розрахунку виразу за допомогою ітеративних конструкцій
def calculate_expression_iterative(A, B):
    start_time = time.time()
    result = np.zeros_like(A)
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            result[i][j] = 2 * (A[i][j] - B[i][j]) * (A[i][j]**2 + B[i][j])
    end_time = time.time()
    execution_time = end_time - start_time
    return result, execution_time

# Матриці A і B
A = np.array([[5, 1, 7], [-10, -2, 1], [0, 1, 2]])
B = np.array([[2, 4, 1], [3, 1, 0], [7, 2, 1]])

# Розв'язок за допомогою ітеративних конструкцій
result_iterative, time_iterative = calculate_expression_iterative(A, B)
print("Результат за допомогою ітеративних конструкцій:")
print(result_iterative)

# Порівняння результатів за допомогою numpy.allclose()
print("Порівняння результатів:", np.allclose(result_numpy, result_iterative))

# Вивід часу виконання для обох підходів
print("Час виконання з використанням універсальних функцій NumPy:", time_numpy, "сек")
print("Час виконання за допомогою ітеративних конструкцій:", time_iterative, "сек")

Result using NumPy:
 [[  162   -30   600]
 [-2678   -30     2]
 [  -98    -6    10]]
Результат за допомогою ітеративних конструкцій:
[[  162   -30   600]
 [-2678   -30     2]
 [  -98    -6    10]]
Порівняння результатів: True
Час виконання з використанням універсальних функцій NumPy: 0.0030281543731689453 сек
Час виконання за допомогою ітеративних конструкцій: 0.0 сек
